### ISSUE TITLE
Clickstream - demo broken on 5.3

### ISSUE THREAD

**Issue by nilnullneil** [hazelcast/hazelcast-platform-demos#129]
May be Cassandra issue 
plus
```Caused by: java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'
	at io.grpc.Metadata$Key.validateName(Metadata.java:754) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$Key.<init>(Metadata.java:762) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$Key.<init>(Metadata.java:671) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:971) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:966) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$Key.of(Metadata.java:708) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.Metadata$Key.of(Metadata.java:704) ~[grpc-api-1.48.0.jar!/:1.48.0]
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:84) ~[grpc-core-1.48.0.jar!/:1.48.0]
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:83) ~[grpc-netty-shaded-1.48.0.jar!/:1.48.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:83) ~[grpc-netty-shaded-1.48.0.jar!/:1.48.0]
	at com.hazelcast.jet.python.DagPythonProcessor.<init>(DagPythonProcessor.java:96) ~[classes!/:?]
	... 39 more```

**Comment by nilnullneil** [comment]
Cassandra is fixed, but cluster still broken

**Comment by nilnullneil** [comment]
Cassandra fixed, https://github.com/hazelcast/hazelcast-platform-demos/issues/153 remains
