### ISSUE TITLE
Transaction Monitor - CLC fails in 5.3

### ISSUE THREAD

**Issue by nilnullneil** [hazelcast/hazelcast-platform-demos#130]
Gives
```
SHOW MAPPINGS;
SHOW VIEWS;
panic: maxWidth should be positive if header is nil

goroutine 1 [running]:
github.com/hazelcast/hazelcast-commandline-client/internal/output.NewTableResult(...)
	/tmp/hazelcast-commandline-client/internal/output/table_result.go:24
github.com/hazelcast/hazelcast-commandline-client/base.(*TablePrinter).PrintStream(0xc00015eb40?, {0xf70b98, 0xc0002f2f80}, {0xf6c560, 0xc0002acad0}, {0xf6b560, 0xc000130928})
	/tmp/hazelcast-commandline-client/base/printers.go:54 +0x11b
github.com/hazelcast/hazelcast-commandline-client/clc/cmd.(*ExecContext).AddOutputStream(0xc00015eb40, {0xf70b98, 0xc0002f2f80}, 0xc0001336e0)
	/tmp/hazelcast-commandline-client/clc/cmd/exec_context.go:124 +0x9b
github.com/hazelcast/hazelcast-commandline-client/base/commands/sql.UpdateOutput({0xf707a8, 0xc000122000}, {0xf72600, 0xc00015eb40}, {0xf710f8, 0xc0002f2f00}, 0x0)
	/tmp/hazelcast-commandline-client/base/commands/sql/common.go:65 +0x3ad
github.com/hazelcast/hazelcast-commandline-client/base/commands.(*ShellCommand).ExecInteractive.func2({0xf707a8, 0xc000122000}, {0xc0002ee520, 0xe})
	/tmp/hazelcast-commandline-client/base/commands/shell.go:121 +0x285
github.com/hazelcast/hazelcast-commandline-client/clc/shell.(*OneshotShell).readTextBasic(0xc000151b28)
	/tmp/hazelcast-commandline-client/clc/shell/oneshot_shell.go:62 +0x287
github.com/hazelcast/hazelcast-commandline-client/clc/shell.(*OneshotShell).Run(...)
	/tmp/hazelcast-commandline-client/clc/shell/oneshot_shell.go:32
github.com/hazelcast/hazelcast-commandline-client/base/commands.(*ShellCommand).ExecInteractive(0xc000130738, {0xf707a8, 0xc000122000}, {0xf72600, 0xc00015eb40?})
	/tmp/hazelcast-commandline-client/base/commands/shell.go:130 +0x4bf
github.com/hazelcast/hazelcast-commandline-client/clc/cmd.(*Main).createCommands.func1(0xc0002ed200, {0xc000293a60, 0x0, 0x2})
	/tmp/hazelcast-commandline-client/clc/cmd/clc.go:308 +0x387
github.com/spf13/cobra.(*Command).execute(0xc0002ed200, {0xc000293a40, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a8300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/hazelcast/hazelcast-commandline-client/clc/cmd.(*Main).Execute(0xc0002d62a0, {0xc00011c160, 0x2, 0x2})
	/tmp/hazelcast-commandline-client/clc/cmd/clc.go:158 +0x165
main.main()
	/tmp/hazelcast-commandline-client/cmd/clc/main.go:29 +0x195
\map entry-set -n __map-store.mysql_slf4j;

```

**Comment by nilnullneil** [comment]
Fixed by https://github.com/hazelcast/hazelcast-platform-demos/pull/198
