### ISSUE TITLE
Transaction Monitor - generic map store failure

### ISSUE THREAD

**Issue by nilnullneil** [hazelcast/hazelcast-platform-demos#155]
See https://github.com/hazelcast/hazelcast/issues/24385

Gives
```
java.lang.NoClassDefFoundError: org/apache/calcite/sql/dialect/CalciteSqlDialect
	at com.hazelcast.mapstore.MappingHelper.<clinit>(MappingHelper.java:34)
	at com.hazelcast.mapstore.GenericMapLoader.init(GenericMapLoader.java:160)
	at com.hazelcast.map.impl.MapStoreWrapper.init(MapStoreWrapper.java:87)
```

**Comment by nilnullneil** [comment]
Tmp fix, added dependency to `abstract-hazelcast-node/pom.xml`

**Comment by nilnullneil** [comment]
Closing as no longer present in 5.5
